number_of_experiments: 3
dataset: "burgers"

search_space_deeponet:
  n_modes: [2]

  branch_network:
    dense_layer:
      layer_width: [256, 512, 1024, 2048]
      activation: ["tanh", "relu"]
      parameter_sampler: ["tanh", "relu"]
    linear_layer:
      regularization_scale: [1e-4, 1e-6, 1e-8, 1e-10]

  trunk_network:
    dense_layer:
      layer_width: [256, 512, 1024, 2048]
      activation: ["tanh", "relu"]
      parameter_sampler: ["tanh", "relu"]
    linear_layer:
      regularization_scale: [1e-4, 1e-6, 1e-8, 1e-10]